name: Bump Version On Push

on: 
  push:
    branches:
      - main

jobs:
  release-on-push:
    name: Release on Push
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: patch